# Generated by Django 3.2.9 on 2022-03-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0003_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='categoty',
            field=models.ManyToManyField(to='article_app.Category'),
        ),
    ]
