# Generated by Django 3.2.9 on 2022-03-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0004_auto_20220319_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categoty',
            new_name='category',
        ),
    ]
