# Generated by Django 3.2.9 on 2022-03-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0005_rename_categoty_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
