# Generated by Django 3.2.9 on 2022-05-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0015_auto_20220501_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
