# Generated by Django 3.2.9 on 2022-06-26 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0019_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 4, 54, 50, 650697, tzinfo=utc)),
        ),
    ]
