# Generated by Django 3.2.9 on 2022-07-17 04:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0022_auto_20220704_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 4, 32, 35, 304388, tzinfo=utc)),
        ),
    ]
